# 配置项目名和session的过期时间
server:
  port: 8888
  servlet:
    context-path: /
    session:
      timeout: 60m
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  tomcat:
    uri-encoding: UTF-8
# 日志的存放位置与级别
logging:
#  pattern:
  #    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
  level:
    root: info
  logback:
    rollingpolicy:
      total-size-cap: 0B
      max-history: 7
      max-file-size: 10MB
  file:
    path: logs
# 配置Mybatis
#mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
  #  静态资源的访问路径
  mvc:
    static-path-pattern: /**
  # 配置数据源
  datasource:
    username: root
    password: cr123!@#
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=Hongkong&useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    # hikari数据源配置，
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 30000
      maximum-pool-size: 20
      max-lifetime: 1800000
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
  #    show-sql: true
  redis:
    database: 1
    host: localhost
    port: 6379
