# 配置项目名和session的过期时间
server:
  port: 8888
  servlet:
    context-path: /
    session:
      timeout: 60m
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  tomcat:
    uri-encoding: UTF-8
# 日志的存放位置与级别
logging:
  file:
    name: log/test.log
  level:
    root: info
# 配置Mybatis
#mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
  #  静态资源的访问路径
  mvc:
    static-path-pattern: /**
  datasource:
    # 配置数据源
    username: root
    password: cr123!@#
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=Hongkong&useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置druid数据源
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true